base_info:
  primary_color: "#0066cc"
  title: cmdragon's Blog
  author: cmdragon
  avatar: /images/avatar.jpg
  logo: /images/logo.svg
  favicon: /images/favicon.ico
  apple_touch_icon: /images/apple-touch-icon.png

menu:
  Home: /                         # 首页
  Archives: /archives             # 归档
  工具箱: https://toolkit.cmdragon.cn
  #  影享天地: https://movie.amd794.com:2083
  #  品影指南: https://movie-guide.amd794.com
  #  漫画宝盒: https://comic.amd794.com:2087
  #  Tags: /tags                   # 标签
  #  Categories: /categories       # 分类
  Links: /links                 # 链接
  #  About: /about                 # 关于
  #  Photos: /photos               # 相册
  # ...

first_screen:
  enable: true        # Option values: true | false
  background_img: /images/bg.svg
  background_img_dark: /images/bg.svg
  description: Keep writing and Keep loving.
  hitokoto: true      # Option values: true | false


social_contact:
  enable: true      # Option values: true | false
  links:
    github: https://github.com/Amd794
    qq: img | /images/qq_group.jpg

scroll:
  progress_bar: true
  hide_header: true

home:
  category: true  # Option values: true | false
  tag: true
  announcement: 我们非常重视您的反馈和建议，欢迎您扫描首页的QQ二维码加入我们的群组，让平台变得更加完善和优秀！

post:
  author_badge:
    enable: true
    level_badge: false
    custom_badge: [ "炼气", "筑基", "结丹", "元婴", "化神","破虚","渡劫","大乘","散仙","真仙","金仙","玄仙","天仙","圣人" ]

  word_count:
    wordcount: true     # Word count, one article. Option values: true | false
    min2read: true      # Time to read, one article. Option values: true | false

  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  copyright_info: true  # Option values: true | false

  share: true           # Option values: true | false

  reward:
    enable: true        # Option values: true | false
    img_link: /images/payment.jpg           # Image link for the payment QR code
    text: 打赏作者一包辣条！               # Custom reward text, Can be null

code_block:
  tools:
    enable: true             # Option values: true | false
    style: default            # Option values: default | mac
  highlight_theme: default    # Option values: default | obsidian

toc:
  enable: true      # Option values: true | false
  number: true      # Option values: true | false
  expand_all: true  # Option values: true | false
  init_open: true    # Option values: true | false
  layout: right      # Option values: left | right

local_search:
  enable: true      # Option values: true | false
  preload: true     # Preload the search data when the page loads

comment:
  enable: false

rss:
  enable: true   # Option values: true | false

lazyload:
  enable: true  # Option values: true | false

cdn:
  enable: false       # Option values: true | false
  provider: cdnjs     # Option values: cdnjs | jsdelivr | unpkg

footer:
  since: 2023           # The starting year of your website, Can be null
  word_count: false     # Option values: true | false

  record:
    enable: false
    list:
      - code: 粤ICP备2024258322号-2
        link: https://beian.miit.gov.cn


  site_deploy:
    enable: true        # Option values: true | false
    provider: github     # Option values: github | vercel | netlify | gitee | aliyun | tencent_cloud | upyun
    url: https://github.com/Amd794                # Your deployment provider url, Can be null

# Mermaid 图表支持
mermaid:
  enable: true     # 是否启用 mermaid
  version: latest  # mermaid 版本号
