name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# 设置权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录以支持分支操作
      
      # 设置Hugo环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # 使用Hugo Extended版本以支持SASS/SCSS
      
      # 构建Hugo项目
      - name: Build with Hugo
        run: hugo
      
      # 部署到public分支
      - name: Deploy to public branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public  # Hugo默认输出目录
          branch: public  # 目标部署分支
          clean: true     # 自动删除目标分支上的旧文件
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token



